name: Build Flutter App (Android)

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build-android:
    name: Build Android APK & AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name:  Run linter
        run: |
          flutter analyze

      - name: Build Android Release
        run: |
          flutter build apk --release
          flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Appbundle
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          
      
